config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources:users, only: [:show,:new,:create] 
  
  resources :shops
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user ,optional: true
  
  validates :name, presence: true, length: { maximum: 100 }
  validates :introduction, presence: true, length: { maximum: 255 }
  validates :time, presence: true, length: { maximum: 50 }
  validates :holiday, presence: true, length: { maximum: 50 }
  validates :phone, presence: true, length: { maximum: 20 }
  validates :address, presence: true, length: { maximum: 200 }
  
  mount_uploader :picture, ImageUploader
  
  geocoded_by :address
  after_validation :geocode
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :shops

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to :shops
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :new, :create, :edit, :update]
  before_action :correct_user,only: [:destroy]
  
  def index
    @shops=Shop.all
  end

  def show
    @shop=Shop.find(params[:id])
  end

  def new
    @shop=Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
    if @shop.save
      flash[:success] = 'Shop が正常に投稿されました'
      redirect_to :shops
    else
      flash.now[:danger] = 'Shop が投稿されませんでした'
      render :new
    end
  end

  def edit
    @user=Shop.find(params[:id]).user
    if @user==current_user
      @shop=Shop.find(params[:id])
    else
      redirect_to :shops
    end
  end

  def update
    @shop=Shop.find(params[:id])
    if @shop.update(shop_params)
      flash[:success] = 'Shopは正常に更新されました'
      redirect_to :shop
     else
      flash.now[:danger] = 'Shopは更新されませんでした'
      render :edit
    end
  end

  def destroy
    @shop.destroy

    flash[:success] = 'Shop は正常に削除されました'
    redirect_to :shops
  end
  
  def shop_params
    params.require(:shop).permit(:name, :picture, :introduction, :time, :holiday, :phone, :user_id, :address, :latitude, :longitude)
  end
  
  def correct_user
    @shop = current_user.shops.find_by(id: params[:id])
    unless @shop
      redirect_to root_url
    end
  end
  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show]
  def show
    @user = User.find(params[:id])
    if @user==current_user
      @shop=@user.shops 
    else
      redirect_to :shops
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to :login
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-light"  style="background-color: #fffacd; ">
    <% if logged_in? %>
    <a class="navbar-brand" href="/shops">Favorite Restaurant</a>
    <% else %>
    <a class="navbar-brand" href="/">Favorite Restaurant</a>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
         <li class="nav-item"><%= link_to '投稿一覧', user_path(current_user), class: 'nav-link' %></li>
         <li class="nav-item"><%= link_to '投稿', new_shop_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %></li>
        <% else %>
          <li class="nav-item"><%= link_to 'ユーザ登録', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Favorite Restaurant</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
    <script src="https://maps.google.com/maps/api/js?key=<%= ENV['GMAP_API_KEY'] %>"></script>
    <script src="https://cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>

  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/shops/edit.html.erb
<div class="row">
  <div class="col-sm-10 offset-sm-1">
    <div class="card">
      <h2 class="card-header text-center">オススメ飲食店編集ページ</h2>
        <div class="card-body">
          <%= form_for @shop do |f| %>
            <div class="form-group">
              <%= f.label :name, '店の名前' %>
              <%= f.text_field :name, class: 'form-control' %>
            </div>
      
            <div class="form-group">
              <%= f.label :picture, '店の画像' %>
              <%= f.file_field :picture, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.label :introduction, '店の紹介文' %>
              <%= f.text_area :introduction, class: 'form-control' %>
            </div>
      
            <div class="form-group">
              <%= f.label :time, '営業時間' %>
              <%= f.text_field :time, class: 'form-control' %>
            </div>
      
            <div class="form-group">
              <%= f.label :holiday, '定休日' %>
              <%= f.text_field :holiday, class: 'form-control' %>
            </div>
      
            <div class="form-group">
              <%= f.label :phone, '電話番号' %>
              <%= f.number_field :phone, class: 'form-control' %>
            </div>
      
            <div class="form-group">
              <%= f.label :address, '住所' %>
              <%= f.text_field :address, class: 'form-control' %>
            </div>

            <%= f.submit '投稿', class: 'btn btn-primary btn-block col-4 offset-4' %>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/shops/index.html.erb
<div class="center jumbotron text-center">
  <h1>オススメ飲食店一覧</h1>
</div>

<div class="row mx-2" style=" display: flex; flex-wrap: wrap;">
  <% @shops.each do |shop| %>
    <div class="col-xs-10 col-sm-6 col-md-4 mb-4 ">
      <div class="card h-100">
        <% if shop.picture.present? %>
        <div class="wrapper">
          <div class="content"><%= image_tag "#{shop.picture}",:width => '100%'%></div>
        </div>
        <% else %>
          <p><%= image_tag '/no image.png',:width => '100%', :height => '100%'%></p>
        <% end %>
      <div class="card-body">
          <div class="card-body text-center">
            <p><%= shop.name %></p>
            <p><%= link_to '詳細ページへ', shop_path(shop),class:'btn btn-outline-success '%></p>
          </div>  
          </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shops/new.html.erb
<div class="row">
  <div class="col-sm-10 offset-sm-1">
  <div class="card">
    <h2 class="card-header text-center">オススメ飲食店投稿ページ</h2>
    <div class="card-body">
    <%= form_with(model: @shop, local: true) do |f| %>
          <%= render 'layouts/error_messages', model: f.object %>

      <div class="form-group">
        <%= f.label :name, '店の名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :picture, '店の画像' %>
        <%= f.file_field :picture, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :introduction, '店の紹介文' %>
        <%= f.text_area :introduction, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :time, '営業時間' %>
        <%= f.text_field :time, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :holiday, '定休日' %>
        <%= f.text_field :holiday, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :phone, '電話番号(ハイフンは不要です)' %>
        <%= f.number_field :phone, class: 'form-control' %>
      </div>
            
      <div class="form-group">
        <%= f.label :address, '住所' %>
        <%= f.text_field :address, class: 'form-control' %>
      </div>
      
      <div class="form-group">
          <%= f.hidden_field :user_id, value: current_user.id %>
      </div>

      <%= f.submit '投稿', class: 'btn btn-primary btn-block col-4 offset-4' %>
    <% end %>

  </div>
  </div>
  </div>
</div>

app/views/shops/show.html.erb
<div class=" center jumbotron text-center">
  <h1>オススメ飲食店詳細ページ</h1>
</div>

<div class="col-sm-12 col-md-8 offset-md-2">
  <div class="text-right">
    <p>投稿日：<%= @shop.created_at.strftime("%Y年%m月%d日") %></p>
  </div>
  <div class="text-center">
    <h2><%= @shop.name %></h2>
      <% if @shop.picture.present? %>
        <p><%= image_tag "#{@shop.picture}"  ,:width => '80%', :height => '60%' %></p>
      <% else %>
        <p><%= image_tag '/no image.png' ,:width => '80%', :height => '60%' %></p>
      <% end %>
    <p><%= simple_format(@shop.introduction) %></p>
    <table class="table table-striped table-bordered  " border="1" style="border-collapse: collapse">
      <tr>
        <td>営業時間</td>
        <td><%= @shop.time %></td>
      </tr>
      <tr>
        <td>店休日</td>
        <td><%= @shop.holiday %></td>
      </tr>
      <tr>
        <td>電話番号</td>
        <td><%= @shop.phone %></td>
      </tr>
      <tr>
        <td>住所</td>
        <td><%= @shop.address %></td>
      </tr>
      <tr>
        <td>アクセス</td>
        <td>
          <div id="map" style='width: 100%; height: 350px;'></div>
          </style>
            <script type="text/javascript">
              handler = Gmaps.build('Google');
              handler.buildMap({ provider: { scrollwheel: false }, internal: {id: 'map'}}, function(){
              markers = handler.addMarkers([
                {
                  "lat": <%= @shop.latitude %>,
                  "lng": <%= @shop.longitude %>,
		              "infowindow": '<p><%= @shop.address %></p><p><%= link_to "Googleマップで見る" ,"https://maps.google.co.jp/maps?q=loc:#{@shop.latitude},#{@shop.longitude}&iwloc=J",target: "_blank" %></p>'
                }
              ]);
              handler.bounds.extendWith(markers);
              handler.fitMapToBounds();
              handler.getMap().setZoom(17);
              });
            </script>
        </td>
      </tr>
    </table>
    <h3>このお店をより多くの人に教えませんか？</h3>
    <%= link_to  "https://twitter.com/share?url=#{request.url}/&text=Favorite Restaurant:#{@shop.name}", title: '共有', target: '_blank' do%>
      <%= image_tag "/Twitter_Social_Icon_Circle_Color.png" ,:width => '70', :height => '70'%>
    <% end %>
  </div>




    <!--<div id="map" style='width: 100%; height: 500px;'></div>-->
</div>

app/views/toppages/index.html.erb
<div class="main-container">
  <h1>Favorite Restaurant</h1>
  <p>みんながオススメする飲食店を共有しよう！</p>
</div>



<div class="text-center">
  <p>このサイトは日本中のユーザがオススメするお店の紹介・投稿・共有が出来るサイトです。</p>
  <p>まずはユーザ登録しよう！</p>
  <%= link_to 'ユーザ登録', signup_path, class: 'btn btn-lg btn-primary' %>
  <div class="mt-4">
    <p>アカウントをお持ちの方はこちらから！</p>
    <p>（リンク先にテスト用のメールアドレスとパスワードを記載してます。）</p>
    <%= link_to 'ログイン', login_path, class: 'btn btn-lg btn-primary' %>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <div class="card">
      <div class="card-header text-center">ユーザ登録</div>
        <div class="card-body">
          <%= form_with(model: @user, local: true) do |f| %>
          <%= render 'layouts/error_messages', model: f.object %>
      
            <div class="form-group">
              <%= f.label :name, 'お名前' %>
              <%= f.text_field :name, class: 'form-control' %>
            </div>
      
            <div class="form-group">
              <%= f.label :email, 'メールアドレス' %>
              <%= f.email_field :email, class: 'form-control' %>
            </div>
      
            <div class="form-group">
              <%= f.label :password, 'パスワード' %>
              <%= f.password_field :password, class: 'form-control' %>
            </div>
      
            <div class="form-group">
              <%= f.label :password_confirmation, 'パスワード（確認用）' %>
              <%= f.password_field :password_confirmation, class: 'form-control' %>
            </div>
            
            <div class="col-4 offset-4">
              <%= f.submit '登録', class: 'btn btn-outline-info offset-4' %>
            </div>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="center jumbotron text-center">
  <h1>あなたの投稿一覧</h1>
</div>

<div class="row mx-2 my-4" style=" display: flex; flex-wrap: wrap;">
  <% @shop.each do |shop| %>
    <div class="col-xs-10 col-sm-6 col-md-4 mb-4 ">
      <div class="card h-100">
        <% if shop.picture.present? %>
          <p><%= image_tag "#{shop.picture}" , :width => '100%'%></p>
        <% else %>
          <p><%= image_tag '/no image.png',:width => '100%', :height => '100%'%></p>
        <% end %>
          <div class="card-body text-center">
            <p><%= shop.name %></p>
            <p><%= link_to '詳細ページへ', shop_path(shop),class:'btn btn-outline-success '%></p>
            <div class="text-right">
              <p><%= link_to 'この投稿を編集する', edit_shop_url(shop) %></p>
              <p><%= link_to 'この投稿を削除する', shop, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %></p>
            </div>
          </div>  
      </div>
    </div>
  <% end %>
</div>